app/ECEC/urls.py
from django.contrib import admin
from django.urls import path, include
from predictor.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('predictor/', include('predictor.urls', namespace='predictor')),
    path('', IndexView.as_view(), name='index'),
]

app/predictor/urls.py
from django.urls import path

from predictor.views import PredictFormView, SuccessView

app_name = 'predictor'

urlpatterns = [
    path('detect/', PredictFormView.as_view(), name='detect'),
    path('success/', SuccessView.as_view(), name='success'),
]

app/predictor/models.py
from django.db import models

# Create your models here.

app/predictor/forms.py
from django import forms
from predictor.content import *

style = forms.Select(attrs={'class': 'form-control'})

class DetectionForm(forms.Form):
    applicant_gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')], widget=style)
    owned_car = forms.ChoiceField(choices=[(0, 'No'), (1, 'Yes')], widget=style)
    owned_realty = forms.ChoiceField(choices=[(0, 'No'), (1, 'Yes')], widget=style)
    total_children = forms.IntegerField(min_value=0, max_value=20, required=True)
    total_income = forms.IntegerField(min_value=0, max_value=9999999, required=True)
    income_type = forms.ChoiceField(choices=income_type, widget=style)
    education_type = forms.ChoiceField(choices=education_type, widget=style)
    family_status = forms.ChoiceField(choices=family_status, widget=style)
    housing_type = forms.ChoiceField(choices=housing_type, widget=style)
    # owned_work_phone = forms.ChoiceField(choices=[(0, 'Yes'), (1, 'No')], widget=style)
    # owned_phone = forms.ChoiceField(choices=[(0, 'Yes'), (1, 'No')], widget=style)
    # owned_Email = forms.ChoiceField(choices=[(0, 'Yes'), (1, 'No')], widget=style)
    job_title = forms.ChoiceField(choices=job_title, widget=style)
    total_family_members = forms.IntegerField(min_value=0, max_value=20, required=True)
    applicant_age = forms.IntegerField(min_value=0, max_value=120, required=True)
    years_of_working = forms.IntegerField(min_value=0, max_value=60, required=True)

app/predictor/views.py
import os
import pickle
from typing import Any

import pandas as pd
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from ECEC.settings import PROJECT_ROOT, GOOGLE_API_KEY
from predictor.content import columns, few_shot_prompt
from predictor.forms import DetectionForm
from google import generativeai


class IndexView(TemplateView):
    template_name = "index.html"

class SuccessView(TemplateView):
    template_name = 'success.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        result = self.request.GET.get("result")
        try:
            context["result"] = result

        except ValueError:
            context["result"] = ''

        return context


class PredictFormView(FormView):
    generativeai.configure(api_key=GOOGLE_API_KEY)
    llm = generativeai.GenerativeModel(
        'gemini-1.5-flash-latest',
        generation_config=generativeai.GenerationConfig(
            temperature=0.1,
            top_p=1,
            max_output_tokens=250,
        )
    )

    form_class = DetectionForm
    template_name = 'predict.html'
    loaded_model = pickle.load(open(os.path.join(PROJECT_ROOT, "best_model_pipeline.pkl"), "rb"))
    # loaded_model = joblib.load(os.path.join(PROJECT_ROOT, "best_model_pipeline.joblib"))

    def form_valid(self, form):
        respone = None
        cleaned_data = form.cleaned_data
        data_list = list(cleaned_data.values())
        result = self.predict(data_list)

        bad_user_data = f"""
        **User's Shared Features**:
        - Gender: {cleaned_data.get('applicant')}
        - Owned Car: {cleaned_data.get('owned_car')}
        - Owned Realty: {cleaned_data.get('owned_realty')}
        - Total Children: {cleaned_data.get('total_children')}
        - Total Income (Annually): {cleaned_data.get('total_income')}
        - Income Type: {cleaned_data.get('income_type')}
        - Education Type: {cleaned_data.get('education_type')}
        - Family Status: {cleaned_data.get('family_status')}
        - Housing Type: {cleaned_data.get('housing_type')}
        - Job Title: {cleaned_data.get('job_title')}
        - Total Family Members: {cleaned_data.get('total_family_members')}
        - Applicant Age: {cleaned_data.get('applicant_age')}
        - Years of Working: {cleaned_data.get('years_of_working')}

        **Feature Importance**:
        - Years of Working: 637
        - Total Income: 600
        - Applicant Age: 581
        - Owned Realty: 204
        - Total Children: 176
        - Total Family Members: 174
        - Owned Car: 169

        **Response**:
        YOUR TURN (DO NOT SUGGEST ABOUT CREDIT HISTORY AND SCORE)
        """

        if result == 0:
            print(type(result))
            response = self.llm.generate_content([few_shot_prompt, bad_user_data]).text
        else:
            response = 'Eligible'

        return redirect(f"{reverse_lazy('predictor:success')}?result={response}")

    def form_invalid(self, form):
        return super().form_invalid(form)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["results"] = getattr(self, "result", None)
        return context

    def predict(self, data):
        data_df = pd.DataFrame([data], columns=columns)
        return self.loaded_model.predict(data_df)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>ECEC</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">ECEC</a>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container text-center mt-5">
    <h1 class="mb-4">Welcome to Easy Credit Eligibility Checker</h1>
    <p class="lead">Check your eligibility for credit in just a few steps!</p>
    <a href="{% url 'predictor:detect' %}" class="btn btn-primary btn-lg mt-3">Get Started</a>
</div>

<footer class="footer mt-5 bg-light text-center py-3">
    <span>© 2024 ECEC - All Rights Reserved</span>
</footer>
{% endblock %}

app/templates/predict.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5">
        <div class="text-center mb-4">
            <h1 class="display-4">ECEC</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a class="btn btn-primary" href="{% url 'index' %}">Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container" style="max-width:600px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <br>
            {% if result != '' and result != 'None' %}
                <div {% if result == "Eligible" %}
                    class="alert alert-success mt-3"
                {% else %}
                    class="alert alert-danger mt-3"
                {% endif %}
                    role="alert">{{ result }}</div>
            {% endif %}

            <br>
            <a class="btn btn-primary" href="{% url 'predictor:detect' %}">Back</a>
        </div>
    </div>
{% endblock %}